version: '3.3'

services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .app_env
    networks:
      - portfolio_network

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    env_file: .db_env
    ports:
      - "3306:3306"
    networks:
      - portfolio_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
networks:
  portfolio_network:
    driver: bridge

volumes:
  mysql-data:
